name: build

on:
  push:
  schedule:
    - cron: '0 0 * * 0' # runs at 00:00 UTC every Sunday

jobs:
  build:
    if: ${{ github.ref == 'refs/heads/main' }}
    permissions:
      packages: write
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      fail-fast: true
      matrix:
        rust-version: [1.82, 1.83, 1.84]
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}/rust
          tags: |
            ${{ matrix.rust-version }}
            ${{ matrix.rust-version == '1.84' && 'latest' || '' }}

      - name: login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: build & push (main)
        uses: docker/build-push-action@v6
        with:
          context: ./build.rust
          push: true
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            RUST_VERSION=${{ matrix.rust-version }}
          tags: ${{ steps.meta.outputs.tags }}
